version: '3.4'

services:

  etebase:
    image: victorrds/etebase:alpine
    user: 0:0
    ports:
      - "3735:3735"
    expose:
      - "3735"
    restart: always
    volumes:
      - etebase-data:/data
    environment:
      - SUPER_USER=...
      - SUPER_PASS=...


  backup:
    image: karbon15/etebase-backup:latest
    restart: always
    # environment:
    #   RCLONE_REMOTE_NAME: 'EtebaseBackup'
    #   RCLONE_REMOTE_DIR: '/EtebaseBackup/'
    #   CRON: '5 * * * *'
    #   ZIP_ENABLE: 'TRUE'
    #   ZIP_PASSWORD: 'WHEREISMYPASSWORD?'
    #   BACKUP_KEEP_DAYS: 0
    #   MAIL_SMTP_ENABLE: 'FALSE'
    #   MAIL_SMTP_VARIABLES: ''
    #   MAIL_TO: ''
    #   MAIL_WHEN_SUCCESS: 'TRUE'
    #   MAIL_WHEN_FAILURE: 'TRUE'
    #   TIMEZONE: 'UTC'
    volumes:
      - etebase-data:/etebase/data/
      - etebase-rclone-data:/config/

volumes:
  etebase-data:
    name: etebase-data
  etebase-rclone-data:
    external: true
